### Volunteers and supporters {#contact}

This study relies on strong and diverse community participation. Social media, email, advertising, and word-of-mouth is needed to reach households with school students.

Reasons to support this study are:



Volunteers may contribute by: displaying posters in workplaces, businesses, or school bus windows; providing translation support; answering questions; sharing information on social media; writing emails and connecting with communities; and may be required to attend a short training session. For a list of volunteers and supporters (see [**here**](#volunteers)). If you are able to be involved in the study design and analysis please email Dr. Amy Hurford.


### Questions
#### What will you be asked for?

The survey will ask you to provide:

1. the first 3 digits of your postal code (i.e., A1A);

1. Regional Health Authority;

1. For both January 22 and 25, the number of:

+ elementary/middle school students in your household that tested negative;

+ elementary/middle school students in your household that tested positive (symptoms/no symptoms);

+ high school students in your household that tested negative;

+ high school students in your household that tested positive (symptoms/no symptoms);

#### What is the purpose of this study?

The study aims to estimate COVID-19 prevalence on January 22 and 25 for school-aged children. This age group has not been widely-tested in Canada during the Omicron wave as some provinces have restricted PCR testing to only individuals older than 70.

Additionally, we will:

- estimate the proportion of asymptomatic cases for school-aged children infected with the Omicron variant;

- evaluate case reporting accuracy when only PCR test results are available;

- evaluate the geographic distribution of cases;

- use these data to parameterize mathematical models that inform public health policy.

#### How will results be reported to participants?
Results submission will end on February 8. Before February 11, we will report the following to this website:

- number of household submissions from each Regional Health Authority;
- percent positivity for each Regional Health Authority;
- percent positivity for elementary/middle schools and high schools;
- percent positive test results reported as asymptomatic;

Results will be most informative if a large number of households from many regions submit their results. If you would like to volunteer please [contact us](#contact). 

#### How is your privacy protected?
No information that can identify your household is submitted. You submit the first 3 digits of your postal code and if the students in your household attend elementary/middle school or high school. The results released publicly on this website will be at the Regional Health Authority and elementary/middle school or high school levels. No data will be reported where there are fewer than 10 positive cases. 

#### Can I report the school?
No. The purpose of this study is to estimate infection in the population of school-aged children. The school that students' attend cannot be reported. 

#### Why do we not use an existing COVID-19 tracker?
This submission portal ensures security and anonymity, and is specific for rapid antigen test use for school students on January 22 and 25. Results will be reported at the same url as the submission portal. This maximizes the chance that participants see the results.

#### Can teachers and administrators submit their results?
No. Teachers and administrators are a small proportion of people in their age group. Collecting data from teachers and administrators will not be sufficient to estimate infection prevalence in their age group.

#### Why are elementary and middle school combined?
Pediatric vaccinations are for 5-12 year olds, which for many students corresponds to elementary and middle school. Contact matrices used in mathematical models consider age ranges spanning multiple years such that it is not necessary to consider middle school separately. 

#### Should I share this initiative on my social media?
Yes! The success of this study depends on strong community participation.

#### Supporters and volunteers {#volunteers}
Memorial University: the Faculties of Science and Education.
